# Generated by Django 4.1.3 on 2022-11-23 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=250)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-nome',),
            },
        ),
    ]
