version : "3"

services:
  backend:
    image : barretolins/backend
    ports: 
      - 8000:8000
  
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:3000